### PR TITLE
fix #207: Additional command names are case-sensitive

### LINKED ISSUE #207: Additional command names are case-sensitive
**Describe the bug**

We have an option for the StringComparison used for options and arguments. But not for commands and subcommands.

Moreover, the base Name of a command is matched ignoring the case but if you define additional names, they are matched in case sensitive mode.

**To Reproduce**

Consider the following test:

```csharp
var app = new CommandLineApplication();
var cmd = app.Command("TEST", c => {
    c.OnExecute(() => 5);
});
cmd.AddName("TE");

app.OptionsComparison

var result = app.Execute("test");
Assert.Equal(5, result);

result = app.Execute("TEST");
Assert.Equal(5, result);

result = app.Execute("te");
Assert.Equal(5, result);

result = app.Execute("TE");
Assert.Equal(5, result);
```

It fails on the 3rd assertion because only the Name is case-insensitive, the additional names are not.

**How to solve the issue**

The issue is actually already pinned in a `TODO` here: https://github.com/natemcmaster/CommandLineUtils/blob/f2818351025b7800bdfe043fea4462dda575b1c1/src/CommandLineUtils/CommandLineApplication.cs#L1006

I suggest to:

- Create a property `public StringComparison CommandsComparison { get; set; }`
- Make it case insensitive by default since this is the actual behavior for the `Name` of a command
- give it the same purpose as `public StringComparison OptionsComparison { get; set; }`
- fix the name match in `src/CommandLineUtils/CommandLineApplication.cs`

@natemcmaster If you agree, I will do the merge request.

### PR DESCRIPTION
**Pull request by jcaillon**
Hello, 

This PR fixes issue #207. I can modify it if needed.

Best regards

### CODE REVIEW

File: src/CommandLineUtils/CommandLineApplication.cs [hunk 1]
```diff
@@ -29,7 +29,7 @@ public partial class CommandLineApplication : IServiceProvider, IDisposable
         private List<Action<ParseResult>> _onParsingComplete;
         internal readonly Dictionary<string, PropertyInfo> _shortOptions = new Dictionary<string, PropertyInfo>();
         internal readonly Dictionary<string, PropertyInfo> _longOptions = new Dictionary<string, PropertyInfo>();
-        private readonly HashSet<string> _names = new HashSet<string>(StringComparer.Ordinal);
```
Comment (natemcmaster) [inline src/CommandLineUtils/CommandLineApplication.cs]: Rather than add a new API, I think I would rather just keep the code as is, but change this to `StringComparer.OrdinalIgnoreCase`. This was a new feature in 2.3 which hasn't seen much usage yet. Now that I think about it, I doubt many users would want subcommands to vary by case, and in 2.2 subcommand name matching was already case-insensitive.

**Comment by natemcmaster** [comment]
Thanks for making the PR. If you can update with my suggestion and make sure the tests are passing, I'll be happy to get this into a patch soon. 

Thanks,
Nate
